[package]
name = "imgui-widgets"
version = "0.1.0"
edition = "2015"
authors = ["rmemr"]

[dependencies.imgui]
version = "0.0.18"
path = "../imgui-rs"

[dependencies.imgui-sys]
version = "0.0.18"
path = "../imgui-rs/imgui-sys"
