[package]
name = "logger"
version = "0.4.2"
edition = "2015"
authors = ["rmemr"]

[dependencies]
log = "0.4"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["consoleapi", "handleapi", "fileapi"] }
